### ISSUE TITLE
 希望能指定群聊和成员，单向转发

### ISSUE THREAD

**Issue by huakair** [hyh19962008/ntchat-wxgroup-sync-bot#2]

**Comment by hyh19962008** [comment]
没太看明白，能描述得具体一点吗？

________________________________
From: huakair ***@***.***>
Sent: Wednesday, July 3, 2024 12:35:08 AM
To: hyh19962008/ntchat-wxgroup-sync-bot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hyh19962008/ntchat-wxgroup-sync-bot] 希望能指定群聊和成员，单向转发 (Issue #2)


―
